services:
  redis:
    container_name: todo_redis
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  backend:
    build: .
    container_name: todo_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
  
  